Exercice 1 : Création et manipulation de réseaux
Instructions
Créez un tableau NumPy 1D contenant des nombres de 0 à 9.

Résultats attendus :
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
import numpy as np

# Création du tableau de 0 à 9
mon_tableau = np.arange(10)

# Affichage du résultat
print(mon_tableau)


[0 1 2 3 4 5 6 7 8 9]


Exercice 2 : Conversion de type et opérations sur l’array
Instructions
Convertissez une liste en tableau NumPy et convertissez son type de données en entier.[3.14, 2.17, 0, 1, 2]

Résultats attendus :

array([3, 2, 0, 1, 2])


In [3]:
import numpy as np

# Liste d'origine
ma_liste = [3.14, 2.17, 0, 1, 2]

# Conversion en tableau NumPy et changement de type en entier
mon_tableau_entier = np.array(ma_liste).astype(int)

# Affichage du résultat
print(mon_tableau_entier)


[3 2 0 1 2]


Exercice 3 : Travailler avec des réseaux multidimensionnels
Instructions
Créez un tableau NumPy 3x3 avec des valeurs allant de 1 à 9.

Résultats attendus :
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
import numpy as np

# Création de la suite de 1 à 9, puis redimensionnement en matrice 3x3
matrice_3x3 = np.arange(1, 10).reshape(3, 3)

# Affichage du résultat
print(matrice_3x3)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


Exercice 4 : Créer un tableau multidimensionnel avec des nombres aléatoires
Instructions
Créez un tableau NumPy 2D de formes (4, 5) remplies de nombres aléatoires.

Résultats attendus :
array([[0.56, 0.85, 0.01, 0.42, 0.68],
       [0.22, 0.37, 0.73, 0.93, 0.39],
       [0.44, 0.03, 0.87, 0.02, 0.83],
       [0.78, 0.87, 0.98, 0.80, 0.46]])

In [5]:
import numpy as np

# Fixer la graine (seed) n'est pas obligatoire, mais cela permet d'obtenir les mêmes nombres à chaque exécution
# np.random.seed(42)

# Création de la matrice 4x5 avec des valeurs aléatoires entre 0 et 1
tableau_aleatoire = np.random.rand(4, 5)

# Affichage du résultat
print(tableau_aleatoire)


[[0.91715106 0.68131812 0.77245681 0.79249065 0.26862076]
 [0.25948082 0.35708451 0.56916561 0.22137487 0.48895179]
 [0.04213476 0.73157088 0.72409686 0.46161141 0.20376007]
 [0.3081203  0.45196965 0.90517596 0.05232955 0.01415361]]


 Exercice 5 : Indexation des tableaux
Instructions
Sélectionnez la deuxième ligne parmi un tableau NumPy 2D donné.

Résultats attendus :
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])

In [6]:
import numpy as np

# Tableau d'origine
array = np.array([[21, 22, 23, 22, 22],
                  [20, 21, 22, 23, 24],
                  [21, 22, 23, 22, 22]])

# Sélection de la deuxième ligne (index 1)
deuxieme_ligne = array[1]

# Affichage du résultat
print(deuxieme_ligne)


[20 21 22 23 24]


Exercice 6 : Inverser les éléments
Instructions
Inversez l’ordre des éléments dans un tableau NumPy 1D donné (le premier élément devient le dernier).

Résultats attendus :
array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [7]:
import numpy as np

# Tableau d'origine
tableau = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Inversion de l'ordre des éléments
tableau_inverse = tableau[::-1]

# Affichage du résultat
print(tableau_inverse)


[9 8 7 6 5 4 3 2 1 0]


Exercice 7 : Matrice d’identité
Instructions
Créez une matrice d’identité 4x4 en utilisant NumPy.

Résultats attendus :
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
import numpy as np

# Création d'une matrice d'identité 4x4
matrice_identite = np.eye(4)

# Affichage du résultat
print(matrice_identite)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Exercice 8 : Fonctions agrégées simples
Instructions
Trouvez la somme et la moyenne d’un tableau 1D donné.

Résultats attendus :
Sum: 45, Average: 4.5

In [9]:
import numpy as np

# Tableau d'origine (de 0 à 9 pour obtenir les résultats attendus)
tableau = np.arange(10)

# Calcul de la somme et de la moyenne
somme = np.sum(tableau)
moyenne = np.mean(tableau)

# Affichage des résultats
print(f"Sum: {somme}, Average: {moyenne}")


Sum: 45, Average: 4.5


Exercice 9 : Créer un tableau et changer sa structure
Instructions
Créer un tableau NumPy avec des éléments allant de 1 à 20 ; Puis remodelez-le en une matrice 4x5.

Résultats attendus :
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [10]:
import numpy as np

# Création du tableau de 1 à 20, puis redimensionnement en matrice 4x5
matrice = np.arange(1, 21).reshape(4, 5)

# Affichage du résultat
print(matrice)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


Exercice 10 : Sélection conditionnelle des valeurs
Instructions
Extraire tous les nombres impairs d’un tableau NumPy donné.

Résultats attendus :
array([1, 3, 5, 7, 9])

In [11]:
import numpy as np

# Tableau d'origine (de 0 à 9)
tableau = np.arange(10)

# Filtrage pour extraire uniquement les nombres impairs
nombres_impairs = tableau[tableau % 2 != 0]

# Affichage du résultat
print(nombres_impairs)


[1 3 5 7 9]
